language: python

python:
    - "2.7"
    - "3.6"

install:
    - pip install numpy scipy matplotlib seaborn corner quadpy emcee iminuit tqdm
    - pip install codecov nose2

    - python setup.py install

script:
    - nose2 --with-coverage

after_success:
    - codecov --token=d875e6f5-ffb8-4a04-8772-cd81b87ccf51
