language: python

python:
    - "2.7"
    - "3.6"

install:
    - pip install numpy
    - pip install scipy
    - pip install matplotlib
    - pip install seaborn
    - pip install corner
    - pip install quadpy
    - pip install emcee
    - pip install iminuit
    - pip install tqdm
    - pip install codecov

    - python setup.py install

script:
    - python tests/tests.py

after_success:
    - codecov --token=d875e6f5-ffb8-4a04-8772-cd81b87ccf51
