language: python

python:
    - "3.8"
    - "3.9"

cache: pip

install:
    - sudo apt-get install graphviz
    - pip install codecov nose2

    - pip install . -r requirements.txt

script:
    - nose2 --with-coverage

after_success:
    - codecov --token=d875e6f5-ffb8-4a04-8772-cd81b87ccf51
