language: python

python:
    - "2.7"
    - "3.6"

cache: pip

install:
    - sudo apt-get install graphviz
    - pip install codecov nose2

    - python setup.py install -r requirements.txt

script:
    - nose2 --with-coverage

after_success:
    - codecov --token=d875e6f5-ffb8-4a04-8772-cd81b87ccf51
